name: CI to Docker hub 

on:
  push:
    branches: [ master ]
  steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: kriive/kurento-frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
